---
name: "Release"
on:  # yamllint disable-line rule:truthy
  push:
    tags:
      - "*"
permissions:
  contents: "write"
  packages: "write"
env:
  GO_VERSION: "~1.20.4"
jobs:
  goreleaser:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v3"
        with:
          fetch-depth: 0
      - uses: "authzed/actions/setup-go@main"
        with:
          go-version: "${{ env.GO_VERSION }}"
      - uses: "authzed/actions/docker-login@main"
        with:
          github_token: "${{ secrets.GITHUB_TOKEN }}"
      - uses: "docker/setup-qemu-action@v1"
      - uses: "docker/setup-buildx-action@v1"
      - uses: "goreleaser/goreleaser-action@v4"
        with:
          distribution: "goreleaser-pro"
          version: "latest"
          args: "release --clean"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
